Online Form :{{$details->code}} Submitted

Customer Name : {{$details->name}}
Mobile Number : {{$details->mobile_no}}
Submitted On : {{date_format($details->created_at, 'd F Y')}}

Login to Form Management System to see the details.

This mail is auto generated by BNBL Form Management System, Please do not reply.