Password Reset for BNBL Form System

OTP for password reset is:

{{$otp}} 

OTP will be valid for 10 minutes
Mistyping OTP for 3 times will render OTP INVALID

This mail is auto generated by BNBL Form Management System, Please do not reply.